spring.application.name=library
server.port=3001

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.yotfxkbnecffsszatsay&password=monkey d luffy&sslmode=require

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update