spring.application.name=library

# Render dynamic port support
server.port=${PORT:3001}

# PostgreSQL (Supabase Pooler)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.yotfxkbnecffsszatsay
spring.datasource.password=monkey d luffy

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true